### PR TITLE
Feature/pretty harmony

### LINKED ISSUE #136: Work on Harmony integration
This is a generic issue to link all harmony related PRs to. Not sure what each piece of Harmony will be, kinda seeing what seems natural.

### LINKED ISSUE #182: persisted assignments in harmony cause issues when trying to find schedule

### PR DESCRIPTION
**Pull request by charkour**
In this PR

- adds the `<footer>` tags to the Footer component
- Creates a Page component
- removes persist middleware from global stores (causing some bugs)
- adds a stepper component to Harmony page
- fixes bugs with the animated title

To test

- go to harmony
- add two professors, four classes, two rooms, two rooms. 
- select all of the assignment checkboxes
- click find schedule
- click send to schedule

There will be one more PR to allow users to import data. I also plan to add better documentation.

Please let me know if there are any issues! Sorry this is so big. I was not anticipating Harmony would take this much work. 

closes #182
links #136

### CODE REVIEW

**Comment by bryantgeorge** [comment]
Tried this with the netlify preview and it said no non-conflicting schedules found:

image

**Comment by bryantgeorge** [comment]
Unsure if this is related to the above comment but using the back button doesn't preserve the state of the previous page (for example if I go back to the page with the checkboxes, the boxes are no longer checked)

**Comment by charkour** [comment]
Thanks for the review! I'll take a look at it soon.

**Comment by charkour** [comment]
@bryantgeorge, I tried your inputs and did not have any issues. I'm not sure what the difference was but it seemed to work. I also used netlify. Thanks again for looking over the PR. I really appreciate it. 

image

**Pull request merged**
