### PR TITLE
Connect Harmony with Schedulizer

### LINKED ISSUE #136: Work on Harmony integration
This is a generic issue to link all harmony related PRs to. Not sure what each piece of Harmony will be, kinda seeing what seems natural.

### PR DESCRIPTION
**Pull request by charkour**
In this PR:

- creates a global results store for harmony results
- converts the harmony output to our schedulizer format
- displays harmony output on a visual schedule
- displays a button to send the created schedule to the schedulizer
- separates schedule components to separate files
- move helper functions below components in same file
- rename props to be `ComponentNameProps` rather than a shadow of `ComponentName`. This allows for easier imports without name conflicts
- adds `readonly` prop to `Schedule` component that does not do anything yet
- add `useAppContext` hook
- add `useRedirect` hook

To test:
- go to harmony page
- add two professors
- add four courses with the format prefix-number-letter
- add two rooms
- add times with the format xx:xx
- click submit on all of the four forms
- then select all checkboxes for the assignments
- then click `find schedule` and a schedule should be found
- then click `send to schedulizer` and the new schedule should show up on the schedulizer page

Right now, Harmony is quite cumbersome to use, do you have suggestions on how to fix that? Maybe a select all checkboxes button and separating the different parts to their own pages with a `PageStepper` component?

Thanks for the comments and critiques!

closes #136

### CODE REVIEW

**Comment by charkour** [comment]
@Jonri2 and @bryantgeorge. This is ready for a brief review.

**Comment by bryantgeorge** [comment]
Unsure why, but I got this on clicking `Find Schedule`:

image

For reference, this was my setup:

image

**Comment by bryantgeorge** [comment]
> Right now, Harmony is quite cumbersome to use, do you have suggestions on how to fix that? Maybe a select all checkboxes button and separating the different parts to their own pages with a PageStepper component?

I think these suggestions sound good. I also think that having a time selector (like our edit/add section popup has) would be good, and I think it's strange that empty fields are counted (just parse these out on submit?). It's probably not worth it to add all of this stuff at this point though, so just do whatever seems necessary.

**Review by bryantgeorge — CHANGES_REQUESTED** [review]
See comments above

**Comment by charkour** [comment]
Thanks for the comments! I agree that the empty fields being part of the submit are weird, I'll make sure to fix that. Also, I'll see if I can get a time selector for the times. Thanks for the suggestions! They are great. 

Also, was the bug you encountered on the Netlify preview or was it locally on your machine? My guess is that it was done locally using an old version of `@harmoniously/react`. Is it possible that you checked out this branch and did not run `npm i`? In the bottom of the stack trace, harmony.ts line 20 shows `as Result`, which was removed in a newer [version of the package](https://github.com/charkour/harmoniously/blob/56cbe840265d383df01a36723feec4fe6a2c29c5/packages/harmoniously/src/harmony.ts#L20) and the bug fixed.

**Comment by bryantgeorge** [comment]
> Thanks for the comments! I agree that the empty fields being part of the submit are weird, I'll make sure to fix that. Also, I'll see if I can get a time selector for the times. Thanks for the suggestions! They are great.
> 
> Also, was the bug you encountered on the Netlify preview or was it locally on your machine? My guess is that it was done locally using an old version of `@harmoniously/react`. Is it possible that you checked out this branch and did not run `npm i`? In the bottom of the stack trace, harmony.ts line 20 shows `as Result`, which was removed in a newer [version of the package](https://github.com/charkour/harmoniously/blob/56cbe840265d383df01a36723feec4fe6a2c29c5/packages/harmoniously/src/harmony.ts#L20) and the bug fixed.

Yeah, that's my bad (I forgot to `npm i` because I assumed since there weren't errors on `npm start` that it was fine). Just tried with the netlify preview and it works great!

**Review by bryantgeorge — APPROVED** [review]
LGTM

**Comment by charkour** [comment]
@bryantgeorge, thanks for the clarification! Sorry I didn't specify `npm i` needed to be run. Glad that the error wasn't anything major. 

Thanks for the review

**Pull request merged**
