### PR TITLE
Feature/chairs meeting cleanup

### PR DESCRIPTION
**Pull request by rpruim**
This PR addresses some urgent things for chairs who will be using the app in Fall 2022:

* #251 -- reduced number of input fields, reorganize a bit to use space better, also relabel a couple fields (and hack a solution to a problem this introduced)
* #250 -- number of output fields has been reduced. Ordering has not been addressed yet (should be easy).

### CODE REVIEW

**Comment by rpruim** [comment]
I'd love to have this approved prior to the chairs meeting tomorrow so that I can demo things with the revised interface and so people who give it a try have something that matches.  Is it possible to get to this today?

**Comment by charkour** [comment]
For urgent PR's, it might be helpful to @ the students or @kvlinden! I don't know enough about the context anymore to feel comfortable approving.

**Review by kvlinden — APPROVED** [review]
I saw this run fine yesterday, but it would be good to get a review from one of the current students (@VelSharon, @FitsumMaru, @samuelth47, @jmw-75

**Review by VelSharon — APPROVED** [review]

**Comment by rpruim** [comment]
Thanks for taking a look.

**Pull request merged**
