### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RyanVreeke**
Merging Develop branch into Production for 2021/2022 Senior Project.

### CODE REVIEW

**Comment by kvlinden** [comment]
I've noticed a few things about this deployment, when running locally, that don't match with the deployed production version:

- I can no longer sort the lines on the teaching-loads page.
- The order of the semesters has reverted to FA-IN-SP; interim should be after spring. 
- I don't see any constraint violations, e.g., the seminar sections don't have red lines.

Are these old fixes working for you? I'm wondering if my local run isn't working properly.

**Review by das43 — APPROVED** [review]
Nice

**Comment by kvlinden** [comment]
We should get this merged for tomorrow, but I haven't heard back on whether the issues I was were there only on my local build or in the actual pull request.

?

**Comment by kvlinden** [comment]
Ryan's email (below) shows the working system - My local copy must be messed up somehow. 

From: Ryan Vreeke 
Sent: Monday, April 11, 2022 3:50 PM
To: senior-knights/course-schedulizer <[reply+AN6ZTJTYHH4B6O5FN3LGZLOAMGVE7EVBNHHEO7AIVY@reply.github.com](mailto:reply+AN6ZTJTYHH4B6O5FN3LGZLOAMGVE7EVBNHHEO7AIVY@reply.github.com)>; senior-knights/course-schedulizer <[course-schedulizer@noreply.github.com](mailto:course-schedulizer@noreply.github.com)>
Cc: Author <[author@noreply.github.com](mailto:author@noreply.github.com)>
Subject: RE: [senior-knights/course-schedulizer] Develop (PR #230)

I believe that may be an old version of the Course Schedulizer. 
Here is the current netlify build which has the up to date develop branch Course Schedulizer: Course Schedulizer (deploy-preview-230--sharp-babbage-a45ee2.netlify.app).
You can test the application out here.

- Ryan

**Review by kvlinden — APPROVED** [review]

**Comment by RyanVreeke** [comment]
I believe that may be an old version of the Course Schedulizer.
Here is the current netlify build which has the up to date develop branch Course Schedulizer: Course Schedulizer (deploy-preview-230--sharp-babbage-a45ee2.netlify.app)<https://deploy-preview-230--sharp-babbage-a45ee2.netlify.app/#/>.
You can test the application out here.

- Ryan

**Pull request merged**
