### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RyanVreeke**
Moving the develop branch into the production branch for the end of Fall semester 2021.
This will be a new stable production release.

### CODE REVIEW

**Comment by RyanVreeke** [comment]
The netlify/sharp-babbage preview is the one that works. If you want to test the merge you can click the Details next to that netlify check to test the version before approving it.

**Review by das43 — APPROVED** [review]
Nice

**Comment by kvlinden** [comment]
looks good to me!

**Review by kvlinden — APPROVED** [review]
all good

**Pull request merged**
