### PR TITLE
Half semester conflict

### PR DESCRIPTION
**Pull request by rpruim**
I improved the test for term overlaps and added low-level tests to confirm that it is working as intended.

### CODE REVIEW

**Comment by rpruim** [comment]
@kvlinden, @charkour -- either one of you want to review this?  It would be nice to get this into production if it isn't causing any problems.

**Comment by charkour** [comment]
I can take a look. 

Would you be willing to email me a schedule I can test with, @rpruim?

**Comment by rpruim** [comment]
I emailed some example files.  There is also a link in #250 to an example from CS.

**Comment by rpruim** [comment]
I think there are some older examples in the repo as well (perhaps used for some of the tests?).  I haven't dug into that too deeply yet, but we should probably create some new import/export tests since we have chanced the import/export process.

**Review by charkour — APPROVED** [review]
Code looks good. Thanks for the unit tests!

**Comment by rpruim** [comment]
I just deployed this.

**Comment by rpruim** [comment]
@charkour, thanks for approving.

@kvlinden, you could load your CS schedule and see if there are any remaining non-conflicts being flagged as conflicts.  I didn't immediately spot any, but you can probably go through the list more quickly than I can since I need to open up the sections to see when they are scheduled and you might just remember.

**Comment by kvlinden** [comment]
The current production branch appears to be working properly. Thanks!

**Pull request merged**
