### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by charkour**
Bryant suggested we merge develop into production after the color by and teaching load features were finished. I think that is a good idea. 

This PR adds:
- Options to export formats
- Minor bug fixes
- Delete a section
- upload .xlsx files
- color by
- teaching loads
- hamony page
- read schedule from url
- save app state

### CODE REVIEW

**Review by charkour — COMMENTED** [review]
A lot of good work

**Review by bryantgeorge — CHANGES_REQUESTED** [review]
I'm getting this on `npm start` (Is there something wrong in my setup?):

```
Failed to compile.

/home/bgeorge/Code/course-schedulizer/client-course-schedulizer/src/components/pages/HarmonyPage/Harmony/Harmony.tsx
TypeScript error in /home/bgeorge/Code/course-schedulizer/client-course-schedulizer/src/components/pages/HarmonyPage/Harmony/Harmony.tsx(1,10):
Module '"../../../../../node_modules/@harmoniously/react/dist"' has no exported member 'Assignments'.  TS2305

  > 1 | import { Assignments, Harmony as H } from "@harmoniously/react";
      |          ^
    2 | import React, { useContext } from "react";
    3 | import { AppContext } from "utilities/contexts";
    4 | 
```

**Comment by charkour** [comment]
I'll try looking into it on my machine. Since Netlify was able to create a preview, it seems there may be an issue with your setup.

**Comment by charkour** [comment]
@bryantgeorge, I was able to `npm i && npm start` with develop. Would you be able to retry that command and report if there are more errors? Thanks.

**Review by Jdellis818 — APPROVED** [review]
LGTM and works on my machine. Though I'd recommend waiting for #151 to merge since that's a fairly significant bugfix.

**Review by bryantgeorge — APPROVED** [review]
> @bryantgeorge, I was able to npm i && npm start with develop. Would you be able to retry that command and report if there are more errors? Thanks.

Hmm, it works now, sorry about that. LGTM (and I agree that we should wait until #151 is done)

**Comment by charkour** [comment]
Sounds good. Thanks guys!

**Pull request merged**
